import os
from svgpathtools import svg2paths2

# This script is bespoke and sensitive to changes

OUTPUT_DIR = "../src/drawing"
POINT_RESOLUTION = 25.0
TARGET_MAX = 1.0 # Scales the drawing so its normalized

def convert_all_svgs():
    script_dir = os.path.dirname(os.path.realpath(__file__))
    abs_output_dir = os.path.join(script_dir, OUTPUT_DIR)

    if not os.path.exists(abs_output_dir):
        os.makedirs(abs_output_dir)

    svg_files = [f for f in os.listdir(script_dir) if f.endswith(".svg")]

    header_path = os.path.join(abs_output_dir, "drawing_data.h")

    with open(header_path, "w") as f:
        f.write('// GENERATED FILE, DO NOT EDIT MANUALLY\n// Generated by: scripts/svg_to_arduino.py\n\n')

        f.write("#pragma once\n")
        f.write("#include <avr/pgmspace.h>\n")
        f.write('#include "drawing/Drawing.h"\n\n')

        # Step 1: Write out all the individual coordinate arrays
        drawing_meta = []
        for svg_file in svg_files:
            svg_path = os.path.join(script_dir, svg_file)
            base_name = (
                os.path.splitext(svg_file)[0].replace(" ", "_").replace("-", "_")
            )
            print("Drawing -> ", base_name)

            try:
                # 1. Capture the svg_attributes (the third return value)
                paths, attributes, svg_attributes = svg2paths2(svg_path)

                # 2. Get the SVG Page Dimensions (ViewBox)
                # We try to get 'viewBox', but fall back to 'width'/'height' if necessary
                if 'viewBox' in svg_attributes:
                    _, _, vw, vh = map(float, svg_attributes['viewBox'].split())
                else:
                    vw = float(svg_attributes.get('width', 100).replace('px', ''))
                    vh = float(svg_attributes.get('height', 100).replace('px', ''))

                # Use the largest dimension as the divisor to keep aspect ratio
                # This ensures the whole 'page' fits into a 0.0 - 1.0 square
                page_max_dim = max(vw, vh)

                raw_points = []
                for path, attr in zip(paths, attributes):
                    # Only process paths that are actually visible
                    if 'style' not in attr:
                            continue

                    if len(path) == 0: continue

                    first_segment = path[0]
                    raw_points.append((first_segment.start.real, first_segment.start.imag))

                    for segment in path:
                        classname = segment.__class__.__name__
                        if classname == 'Line':
                            raw_points.append((segment.end.real, segment.end.imag))
                        else:
                            # Adaptive sampling based on length
                            num_samples = max(2, int(segment.length() / POINT_RESOLUTION))
                            for s in range(1, num_samples + 1):
                                p = segment.point(s / num_samples)
                                raw_points.append((p.real, p.imag))

                if not raw_points:
                    continue

                # 3. Write array using Global Scale
                f.write(f"const float {base_name}_pts[][2] PROGMEM = {{\n")
                for x, y in raw_points:
                    # Scale based on the page size, NOT the point range
                    nx = (x / page_max_dim) * TARGET_MAX
                    # In SVGs, Y increases downwards. We flip it for standard Cartesian.
                    ny = (1.0 - (y / page_max_dim)) * TARGET_MAX
                    f.write(f"  {{ {nx:.4f}f, {ny:.4f}f }},\n")
                f.write("};\n\n")

                drawing_meta.append(
                    {
                        "var": f"{base_name}_pts",
                        "count": len(raw_points),
                        "name": base_name.replace("_", " ").title(),
                    }
                )
            except Exception as e:
                print(f"Failed {svg_file}: {e}")

        # Step 2: Define the Struct and the Collection
        f.write(f"const Drawing ALL_DRAWINGS[{len(drawing_meta)}] = {{\n")
        for meta in drawing_meta:
            f.write(f"    {{ \"{meta['name']}\", {meta['var']}, {meta['count']} }},\n")
        f.write("};\n\n")

        f.write(f"const int DRAWINGS_COUNT = {len(drawing_meta)};\n\n")

    print(f"Done! Generated {len(drawing_meta)} drawings in drawings_data.h")


if __name__ == "__main__":
    convert_all_svgs()
